---
- name: Install Apache Web Server
  hosts: all
  become: yes

  tasks:
    - name: Install Apache (httpd) on RedHat/CentOS
      yum:
        name: httpd
        state: present  
      when: ansible_os_family == "RedHat"

    - name: Install Apache (apache2) on Debian/Ubuntu
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ensure Apache is running and enabled
      service:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: started
        enabled: yes
