---
- name: install webserver with handler
  hosts: all
  tasks:
  - name: launch webserver use template
    apt:
      name: apache2
      state: present
      update_cache: yes
  - name: copy template file to documentroot
    template:
      src: index.j2
      dest: /var/www/html/index.html
    notify: restart_service
  handlers:
  - name: restart_service
    service:
      name: apache2
      state: restarted







